### ISSUE TITLE
Docker ignores smtp port

### ISSUE THREAD

**Issue by mrhteriyaki** [SMTP2Graph/SMTP2Graph#14]
The config.yml port configuration appears to be ignored by the docker version, it looks like the port is being set in the startup script.
Can this be adjusted to read the config file for the port? 

I've got an example that read the file for the port number.
[Example](https://github.com/mrhteriyaki/SMTP2Graph/blob/main/docker/startup.sh)

**Comment by RoelVB** [comment]
Thank you for the report. This was a dumb design choice on my side.
It's fixed in version 1.0.2
