### ISSUE TITLE
Add HTTP proxy support

### ISSUE THREAD

**Issue by RoelVB** [SMTP2Graph/SMTP2Graph#18]
To be able to connect to the Graph API over a proxy.
As mentioned here: https://github.com/SMTP2Graph/SMTP2Graph/issues/16#issuecomment-2202895433

**Comment by pandel** [comment]
Just wanted to say: Wow! You have been very fast adding this new feature! And MANY MANY THANKS! It is working perfectly against a proxy with authentication!

**Comment by RoelVB** [comment]
@pandel 
Thanks for the update. Good to hear it's working for you.

Feel free to donate/sponsor if you like my work 😉
