### ISSUE TITLE
Messages seem to drop To and From so fail to leave the queue

### ISSUE THREAD

**Issue by barryboden** [SMTP2Graph/SMTP2Graph#23]
Testing with Telnet to the SMTP server, however all the messages are stuck in the queue.
`HELO test.example.com`
`MAIL From: <test@example.com>`
`RCPT To: <test@example.com>`
`DATA`
`Subject: Test Email`
`This is a test email sent via Telnet.`
`.`
`QUIT`

When I look in the queue folder the messages have no To or From lines, if it edit them to add, they will send when the restarting.
Are the SMTP commands case sensitive or am i missing something

**Comment by barryboden** [comment]
Looks like AI giving bad command examples and the To and From should be repeated after DATA.

**Comment by RoelVB** [comment]
Hi @barryboden 

Could it be that you tried this on v1.1.0 and not v1.1.1? (the later was release October 19th)

The `RCPT TO:` in the SMTP session could also contain BCC recipients. After `DATA`, the recipients can be split to `To`, `Cc` and `Bcc` using the headers.

As of v1.1.1, SMTP2Graph assumes any recipients that are not in the `To` or `Cc` headers to be `Bcc` recipients. So in theory the message could still leave the queue with only `Bcc` recipients (although I have to check if the Graph API actually accepts this).

**Comment by barryboden** [comment]
Thanks for taking a look, I was using the 1.1.1 version.
It was a failure on my part as I trusted copilot to give me an example smtp exchange which I then used via telnet to test it.   
  
This example didn't include the To: or From: after DATA.
The messages then sat in the queue, they did have Bcc: but it wasn't until I edited the queued messages and included  From: that were able to send.    

I'm happy to accept this is my fault rather than an issue.   If you want you could using similar logic to your force Bcc include the "From:" if its missing using either the same address given in MAIL From: or the forceMailbox: address from the config.  

Thanks again for you time.

**Comment by RoelVB** [comment]
Fixed in v1.1.2
